server:
  port: 8083
spring:
  application:
    name: springCloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/justlikeliuen/config-repo.git
          clone-on-start: true
      override-none: true
#The HTTP service has resources in the form:
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties

#{application} maps to "spring.application.name" on the client side;
#{profile} maps to "spring.profiles.active" on the client (comma separated list); and
#{label} which is a server side feature labelling a "versioned" set of config files.