server:
  port: 8080
spring:
  application:
    name: springCloudConfig
  cloud:
    config:
      server:
        git:
          uri: F:///git/config-repo
          clone-on-start: true
#The HTTP service has resources in the form:
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties

#{application} maps to "spring.application.name" on the client side;
#{profile} maps to "spring.profiles.active" on the client (comma separated list); and
#{label} which is a server side feature labelling a "versioned" set of config files.