spring:
  application:
    name: eurekaServer
server:
  port: 18086

eureka:
  instance:
    hostname: peer2
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://peer1:18085/eureka/,http://peer3:18087/eureka/"
    #    serviceUrl指向与本地实例相同的主机。
